server:
  port: 8090
spring:
  data:
    mongodb:
      username: ejrosalesp
      password: ejrosalesp
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin