spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${port.server}/eureka/

server:
  port: 8761
